nvidia:
  compiler:
      - toolchain: gcc
        spec: gcc
      - toolchain: llvm
        spec: nvhpc
  unify: when_possible
  mpi:
      spec: cray-mpich@8.1.29%nvhpc
      gpu: cuda
  specs:
  - boost ~mpi
  - python@3.10
  - cmake
  - cuda@12.3
  - hdf5
  - hwloc
  - libfyaml
  - netcdf-c
  - netcdf-cxx4
  - netcdf-fortran%nvhpc
  - numactl
  - osu-micro-benchmarks@5.9%nvhpc
  # everything needed for nccl on SS11
  - aws-ofi-nccl@master
  - nccl
  - nccl-tests
  variants:
  - cuda_arch=90
  - +mpi
  - +cuda
  packages:
  - curl
  - gmake
  - perl
  views:
    icon:
      link: roots
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]

