name: prgenv-gnu-openmpi
spack:
  repo: https://github.com/spack/spack.git
  commit: v1.1.1
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: 107d3dbda28f475b2f0f241a407fc92787d821c7 # develop on 2026-03-12
store: /user-environment
description: GNU Compiler toolchain with OpenMPI, Python, CMake and other development tools.
version: 2
