name: mch
store: /mch-environment/v8
spack:
  commit: releases/v0.22
  repo: https://github.com/spack/spack.git
description: The compiler toolchains, libraries and tools required for the MCH production software stack.
