prgenv-gcc:
  compiler:
    - toolchain: gcc
      spec: gcc
  unify: when_possible
  mpi:
    spec: cray-mpich@8.1.30%gcc
  packages:
  - perl
  - libx11
  - gmake
  - autoconf
  - automake
  specs:
  - osu-micro-benchmarks@5.9
  - openblas@0.3.21
  - libfyaml@0.7.12
  - hdf5@1.12.2 +fortran +threadsafe ~mpi
  - hdf5@1.12.2 +fortran +threadsafe +mpi
  - netlib-scalapack@2.2.0
  #- eccodes@2.25.0 +tools +fortran +aec +openmp jp2k=jasper
  - eccodes@2.34.0 +tools +fortran +aec +openmp jp2k=jasper
  - netcdf-c@4.8.1+mpi ^hdf5+mpi api=v18
  - netcdf-c@4.8.1~mpi ^hdf5~mpi api=v18
  - netcdf-fortran@4.5.4 ^netcdf-c+mpi
  - netcdf-fortran@4.5.4 ^netcdf-c~mpi
  variants:
  - +mpi
  views:
    prgenv-gcc-serial:
      exclude:
      - hdf5+mpi
      - netcdf-c+mpi
      - netcdf-fortran ^netcdf-c+mpi
      - eccodes@2.25.0
      link: roots
