gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc@13
  mpi:
      spec: cray-mpich@8.1.30
      gpu: Null
  unify: true
  specs:
  - arpack-ng
  - boost +atomic +chrono +container +context +coroutine +date_time +filesystem +iostreams +json +log +mpi +multithreaded +program_options +python +random +regex +serialization +shared +system +test +thread +timer +url
  - cmake
  - eigen
  - fftw
  - fmt
  - gsl
  - hdf5 +fortran +hl
  - hwloc
  - hypre +superlu-dist
  - kokkos +aggressive_vectorization cxxstd=17 +hwloc +openmp +pic +serial +shared ~tuning
  - kokkos-kernels +blas +execspace_openmp +execspace_serial +lapack +openmp scalars=float,double,complex_float,complex_double +serial +shared +superlu
  - kokkos-tools +mpi +papi
  - metis
  - mumps +parmetis +ptscotch
  - netcdf-c
  - netlib-scalapack
  - lua
  - libtree
  - lz4
  - meson
  - nco
  - ninja
  - openblas threads=openmp
  - osu-micro-benchmarks@5.9
  - p4est +mpi
  - parmetis
  - petsc +batch +hwloc +hypre +kokkos +libyaml +metis +mumps +openmp +ptscotch +suite-sparse
  - python@3.12
  - slepc
  - suite-sparse
  - superlu
  - superlu-dist
  - swig
  - trilinos@16 +adios2 ~amesos +amesos2 +belos +boost cxxstd=17 ~epetra ~epetraext +explicit_template_instantiation +hdf5 +hypre ~ifpack +ifpack2 +intrepid2 +kokkos ~ml +mpi +muelu +mumps +nox +openmp +sacado +stk +stratimikos +suite-sparse +superlu-dist +tpetra +zoltan2
  - zlib-ng
  variants:
  - +mpi
  views:
    default:
      link: roots
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
