name: lammps
store: /user-environment
description: LAMMPS with and without Plumed, and the toolchain to build your own LAMMPS.
spack:
  repo: https://github.com/spack/spack.git
  commit: v0.20
modules: True
