#!/bin/bash

echo "====================================="
echo "=====     post install hook     ====="

mount_path={{ env.mount }}
echo RUNNING IN $mount_path
config_path={{ env.config }}
echo config is in $config_path

echo
echo "=====   environment variabls    ====="
printenv

echo
echo "=====   create post file {{ env.mount }}/post  ====="
echo "$(date)" > "$mount_path/post"

echo
echo "===== list all spack packages ====="
spack -C $config_path find

echo "====================================="

# =====================================
# we need to source the spack environment before using 'spack load' etc
#. ./spack/share/spack/setup-env.sh

eval `spack -C $config_path load --sh gcc@11 % gcc@11`
eval `spack -C $config_path load --sh paraview +egl`
eval `spack -C $config_path load --sh tbb`
eval `spack -C $config_path load --sh cuda`

PARAVIEW_DIR=$( spack -C $config_path location -i 'paraview + egl' )

git clone https://github.com/jfavre/ParaViewGadgetPlugin
cd ParaViewGadgetPlugin/
mkdir build; cd build
cmake -S .. \
      -DCMAKE_INSTALL_PREFIX=$mount_path/paraview-plugins    \
      -DParaView_DIR=$PARAVIEW_DIR/lib64/cmake/paraview-5.11
make -j
make install

find $mount_path/paraview-plugins
