tools:
  compiler:
    - toolchain: gcc
      spec: gcc@11.3
  unify: when_possible
  specs:
  - cmake
  - python@3.7
  - python@3.10
  - libtree
  - tree
  - ruby@3.1.0
  - r@4.0.5
  packages:
  - perl
#prgenv-nvidia:
#  compiler:
#    - toolchain: gcc
#      spec: gcc@11.3
#    - toolchain: llvm
#      spec: nvhpc
#  unify: when_possible
#  mpi:
#    spec: cray-mpich@8.1.18.4
#    gpu: cuda
#  packages:
#  - perl
#  - curl
#  specs:
#  - osu-micro-benchmarks@5.9%nvhpc
#  - cuda@11.8%gcc
#  - eccodes@2.25.0%nvhpc +tools +fortran +aec +openmp jp2k=jasper
#  - eccodes@2.19.1%nvhpc +tools +fortran +aec +openmp jp2k=jasper
#  - netcdf-c@4.8.1%nvhpc
#  - netcdf-fortran@4.5.4%nvhpc
#  - openblas@0.3.21%nvhpc
#  - libfyaml@0.7.12%nvhpc
  # these are explicitly concretised with gcc
  #- autoconf%gcc
  #- automake%gcc
  #- ca-certificates-mozilla%gcc
  #- diffutils%gcc
  #- gnuconfig%gcc
  #- libiconv%gcc
  #- libsigsegv%gcc
  #- libxcrypt%gcc
  #- libxml2%gcc
  #- m4%gcc
  #- ncurses%gcc
  #- openssl%gcc
  #- xz%gcc
  #- zlib%gcc
  #- zstd%gcc
  #- c-blosc%gcc
  #- libaec%gcc
  #- jasper%gcc
  #- patchelf%gcc
  #- gmake%gcc
#  variants:
#  - cuda_arch=80
#  - +mpi
#  - +cuda
prgenv-gcc:
  compiler:
    - toolchain: gcc
      spec: gcc@11.3
  unify: when_possible
  mpi:
    spec: cray-mpich@8.1.25
    gpu: null
  packages:
  - perl
  - curl
  specs:
  - cuda@11.8
  - osu-micro-benchmarks@5.9
  - openblas@0.3.21
  - libfyaml@0.7.12
  - hdf5@1.12.2 +fortran +threadsafe ~mpi
  - hdf5@1.12.2 +fortran +threadsafe +mpi
  - netlib-scalapack@2.2.0
  - eccodes@2.25.0 +tools +fortran +aec +openmp jp2k=jasper
  - netcdf-c@4.8.1+mpi ^hdf5+mpi api=v18
  - netcdf-c@4.8.1~mpi ^hdf5~mpi api=v18
  - netcdf-fortran@4.5.4 ^netcdf-c+mpi
  - netcdf-fortran@4.5.4 ^netcdf-c~mpi
  - nco@5.0.1
  - cdo@2.0.5
  variants:
  - cuda_arch=80
  - +mpi
  - +cuda

#nvidia:
# compiler:
#     - toolchain: gcc
#       spec: gcc
#     - toolchain: llvm
#       spec: nvhpc
# unify: when_possible
# mpi:
#     spec: cray-mpich
#     gpu: cuda
# specs:
# - eccodes@2.25.0%nvhpc +tools +fortran +aec +openmp jp2k=jasper
# - cmake%gcc
# - cuda@11.8%gcc
# - hdf5%nvhpc +fortran
# - hwloc%gcc
# - netcdf-c%gcc
# - netcdf-fortran%nvhpc
# - numactl%gcc
# - osu-micro-benchmarks@5.9%nvhpc
# - perl%gcc
# # The following are required to stop spack from using nvhpc to build
# # basic dependencies, some of which don't compile with nvc etc.
# # Explicitly excluded as modules.
# - autoconf%gcc
# - automake%gcc
# - ca-certificates-mozilla%gcc
# - diffutils%gcc
# - gnuconfig%gcc
# - libiconv%gcc
# - libxcrypt%gcc
# - libxml2%gcc
# - m4%gcc
# - ncurses%gcc
# - openssl%gcc
# - xz%gcc
# - zlib%gcc
# - zstd%gcc
# - c-blosc%gcc
# - libaec%gcc
# - jasper%gcc
# - patchelf%gcc
# - gmake%gcc
# variants:
# - cuda_arch=80
# - +mpi
# - +cuda
# packages:
# - curl
# - gmake
# views:
#   default:
