gcc-nvgpu:
  compiler:
  - toolchain: gcc
    spec: gcc@11.3
  mpi:
    spec: cray-mpich
    gpu: cuda
  unify: true
  specs:
  - cmake
  - ninja
  - python
  - paraview@5.11 +egl    build_edition=rendering +cuda +mpi +opengl2 +tbb +python use_vtkm=on
  packages:
  - perl
  - diffutils
  - gettext
  - openssh
  - openssl
  - ncurses
  - cpio
  variants:
  - +cuda
  - cuda_arch=80
  - ~fortran
  - build_type=Release
  - cxxstd=17
  - ~examples

gcc-nvgpu2:
  compiler:
  - toolchain: gcc
    spec: gcc@11.3
  mpi:
    spec: cray-mpich
    gpu: cuda
  unify: true
  specs:
  - cmake
  - ninja
  - python
  - paraview@5.11 +egl    build_edition=rendering +cuda +mpi +opengl2 +tbb +python use_vtkm=off
  packages:
  - perl
  - diffutils
  - gettext
  - openssh
  - openssl
  - ncurses
  - cpio
  variants:
  - +cuda
  - cuda_arch=80
  - ~fortran
  - build_type=Release
  - cxxstd=17
  - ~examples

gcc-nvgpu3:
  compiler:
  - toolchain: gcc
    spec: gcc@11.3
  mpi:
    spec: cray-mpich
    gpu: cuda
  unify: true
  specs:
  - cmake
  - ninja
  - python
  - paraview@5.11 +osmesa build_edition=rendering ~cuda +mpi +opengl2 +tbb +python use_vtkm=default
  packages:
  - perl
  - diffutils
  - gettext
  - openssh
  - openssl
  - ncurses
  - cpio
  variants:
#  - +cuda
  - cuda_arch=80
  - ~fortran
  - build_type=Release
  - cxxstd=17
  - ~examples
