gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc
  mpi:
      spec: cray-mpich@8.1.30
      gpu: false
  unify: true
  specs:
  - hdf5
  - netcdf-c
  - netcdf-cxx4
  - netcdf-fortran
  - ncview
  - cdo
  - nco
  - python@3.12
  #- ferret
  views:
    default:
      link: roots
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
  packages:
  - git
  - perl

