stages:
  - build
  - test

.base-build:
  stage: build
  variables:
    SLURM_TIMELIMIT: 180
  script:
  - ./stack-build -n $STACK_NAME -s $STACK_SYSTEM -r $STACK_RECIPE -b /dev/shm/jenkssl $SPACK_DEVELOP
  after_script:
  - rm -Rf /dev/shm/jenkssl
  artifacts:
    paths:
    - artifacts/

.base-test:
  stage: test
  variables:
    SLURM_TIMELIMIT: 30
    GIT_STRATEGY: fetch
  script:
  - ./run-reframe -n $STACK_NAME -s $STACK_SYSTEM
  artifacts:
    when: always
    paths:
    - report.xml
    reports:
      junit: report.xml


build-gromacs:2023-clariden:a100:
  extends: .base-build
  tags: ["clariden-spack-stack-builder"]
  variables:
    SPACK_DEVELOP:    ""
    STACK_NAME:       "gromacs"
    STACK_SYSTEM:     "clariden"
    SLURM_PARTITION:  "nvgpu"
    STACK_RECIPE:     "None"

test-gromacs:2023-clariden:a100:
  extends: .base-test
  tags: ["clariden-login-baremetal"]
  variables:
    STACK_NAME:       "gromacs"
    STACK_SYSTEM:     "clariden"
    SLURM_PARTITION:  "nvgpu"
