gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc@13
  mpi:
      spec: cray-mpich@8.1.32%gcc
      gpu: cuda
  unify: true
  specs:
  - q-e-sirius@1.0.1 hdf5=parallel
  - sirius@7.7.1
  - spfft+gpu_direct
  variants:
  - cuda_arch=90
  views:
    default:
