gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc
  mpi:
      spec: cray-mpich@8.1.32
  unify: when_possible
  specs:
  - q-e-sirius@1.0.1 hdf5=parallel
  - sirius@7.8 +nlcglib
  - nlcglib@1.3.0
  variants:
  - +mpi
  views:
    default:
      link: roots
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
