gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc@11
  mpi:
      spec: cray-mpich
      gpu: Null
  unify: true
  specs:
  - cmake
  - cuda@11.8
  - python@3.11
  - py-mpi4py
  - py-h5py
  - py-numpy
  - py-pybind11
  - py-pip
  - py-pyyaml
  - py-scipy
  - py-voluptuous
  - intel-oneapi-mkl
  - libxc@5.2.3~cuda
  - gsl
  - hdf5
  - costa
  - eigen
  - spfft +cuda cuda_arch=80
  - spla +cuda
  - spglib
  variants:
  - +mpi
  packages:
  - perl
  - git
  - pkgconf
  - readline
  - ncurses
  - patchelf
  - diffutils
  - libiconv
  - openssl
  - sqlite
  - tar
  - libxml2
  - gettext

nvhpc-env:
  compiler:
      - toolchain: llvm
        spec: nvhpc@23.3
      - toolchain: gcc
        spec: gcc@11
  unify: true
  specs:
  - libxc@5.2.3%nvhpc~cuda
  - cuda@11.8%gcc
  - patchelf%gcc
  mpi:
      spec: cray-mpich
      gpu: Null
  packages:
  - perl
