gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc@11
  mpi:
      spec: cray-mpich
      gpu: Null
  unify: true
  specs:
    #- cmake
  - cuda@11.8
  - python@3.11
  - py-mpi4py
  - py-h5py
  - py-numpy
  - py-pybind11
  - py-pip
  - py-pyyaml
  - py-scipy
  - py-voluptuous
    #  - openblas threads=openmp
  - libxc@5.2.3~cuda
  - gsl
  - hdf5
  - costa
  - eigen
  - spfft +cuda
  - spla +cuda
  - spglib
  variants:
  - +mpi
  - +cuda
  - cuda_arch=80
  packages:
  - perl
  - git
  - pkgconf
  - readline
  - ncurses
  - patchelf
  - diffutils
  - libiconv
  - openssl
  - sqlite
  - tar
  - libxml2
  - gettext
  views:
    gcc-env:

nvhpc-env:
  compiler:
      - toolchain: llvm
        spec: nvhpc@22.5
      - toolchain: gcc
        spec: gcc@11
  mpi:
      spec: cray-mpich
      gpu: Null
  unify: true
  specs:
  - cmake%gcc
  - libxc@5.2.3%nvhpc~cuda
  - cuda@11.8%gcc
  - patchelf%gcc
  - openblas%gcc threads=openmp
  - quantum-espresso@7.1 %nvhpc +libxc +cuda ^openblas threads=openmp ^cray-mpich ^libxc@5.2.3%nvhpc~cuda
  variants:
  - +mpi
  - +cuda
  - cuda_arch=80
  packages:
  - perl
  - git
  views:
    nvhpc-env:
