scorep:
  compiler:
  - toolchain: gcc
    spec: gcc@12
  unify: when_possible
  mpi:
    spec: cray-mpich@8.1.30
    gpu: cuda
  specs:
  # keeping for reference:  
  # - cmake
  # - hdf5 +cxx +hl ~fortran
  - scalasca@2.6.2 ^scorep@9.0 +cuda +mpi ~papi +gotcha +unwind ^libunwind ^binutils +libiberty ^cuda@12
  views:
    default:
      link: all
