gromacs:
  compiler:
      - toolchain: gcc
        spec: gcc@11
  mpi:
      spec: cray-mpich
      gpu: cuda
  unify: when_possible
  specs:
  - cmake
  - cuda@11.8
  - gromacs@2023.1 +cuda +blas +lapack +hwloc
  - gromacs@2022.5 +plumed +cuda +blas +lapack +hwloc
  - hwloc
  - python@3.10
  variants:
  - +mpi
  - +cuda
  - cuda_arch=80
  views:
    develop:
      exclude: ['gromacs']
    gromacs:
      exclude: ['gromacs+plumed']
      link: run
    plumed:
      exclude: ['gromacs@2023.1']
      link: run
  packages:
  - perl

