gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc
  mpi: null
  unify: true
  specs:
  - zlib-ng
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90
  views:
    default:
      link: roots
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
