name: prgenv-gnu
version: 2
spack:
  commit: releases/v1.0
  repo: https://github.com/spack/spack.git
  packages:
    repo: https://github.com/msimberg/spack-packages.git
    commit: aws-ofi-nccl-with-rocm-old-develop # develop on 2025-12-19 + https://github.com/spack/spack-packages/compare/develop...msimberg:spack-packages:aws-ofi-nccl-with-rocm-old-develop
description: GNU Compiler toolchain with cray-mpich, Python, CMake and other development tools for gfx90a, gfx942 (MI300A, MI250X)
