version: 2
name: nvidia-mp
description: NVIDIA libraries
spack:
  repo: https://github.com/spack/spack.git
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: alby/new-package-cufftmp
store: /user-environment
modules: false
