lammps:
  compiler:
  - toolchain: gcc
    spec: gcc@12.3
  mpi:
    spec: cray-mpich@8.1.28
    gpu: cuda
  unify: true
  specs:
  - cuda@12
  - kokkos@develop +wrapper
  - lammps@develop
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90
  - +kokkos@develop
  views:
    default:
      link: run
  packages:
  - perl
