lammps-kokkos:
  compiler:
  - toolchain: gcc
    spec: gcc@13
  mpi:
    spec: cray-mpich@8.1.30
  unify: true
  specs:
  - python@3.11
  - cmake
  - kokkos@4.4.01 +openmp
  # lammps + kokkos package
  - lammps@20240829.1 +kokkos +python +extra-dump +plumed +replica +extra-molecule +openmp
  variants:
  - +mpi
  views:
    develop-kokkos:
      link: all
      exclude: ["lammps"]
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
    kokkos:
      link: all
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]