name: hpctoolkit
store: /user-tools
spack:
  repo: https://github.com/spack/spack.git
  commit: releases/v1.2
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: releases/v2026.06
default-view: 'hpctoolkit'
description: 'HPCToolkit is an integrated suite of tools for measurement and analysis of program performance'
version: 3
