hpctoolkit-env:
  compiler: [gcc]
  unify: true
  network:
    mpi: cray-mpich@9.1.0+cuda
  specs:
    - flamegraph
    - py-hatchet 
    - hpctoolkit@2026.0.stable +cuda +python ~viewer buildtype=debug build_system=meson
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90
  views:
    hpctoolkit:
      link: all
