#!/usr/bin/python3

import yaml

with open("{{ env.mount }}/config/packages.yaml", mode='r') as file:
    packages = yaml.safe_load(file)

packages['all'] = {'variants': 'cuda_arch=80'}

with open("{{ env.mount }}/config/packages.yaml", mode='w') as file:
    yaml.dump(packages, file)
