name: prgenv-nvfortran
spack:
  commit: releases/v0.22
  repo: https://github.com/spack/spack.git
store: /user-environment
description: NVIDIA compiler toolchain (nvhpc) with cray-mpich, Python, CMake and other development tools.
