editors:
  compiler: [gcc]
  unify: true
  network:
    mpi: null
  specs:
  # the editors
  #- 'emacs +treesitter +native' # maybe breaks concretizer
  - 'nano'
  - 'vim +python +lua'
  - 'neovim'
  - 'direnv'
  - 'fd'
  - 'lazygit'
  - 'lua'
  - 'python'
  - 'ripgrep'
  #- 'screen' # breaks the concretizer
  - 'tree-sitter'
  # filebrowser
  - 'py-ranger-fm'
  - 'nnn'
  - 'tmux'
  - 'fzf'
  views:
    editors:
      link: roots
      uenv:
        add_compilers: false
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
