editors:
  compiler: [gcc]
  unify: true
  network:
    mpi: null
  specs:
  # editors
  - 'emacs +treesitter'
  - 'nano'
  - 'vim +python +lua'
  - 'neovim'
  - 'tree-sitter'
  # handy CLI tools
  - 'direnv'
  - 'fd'
  - 'lazygit'
  - 'ripgrep'
  # building stuff
  - 'cmake'
  - 'meson'
  - 'ninja'
  # session management
  - 'screen'
  - 'tmux'
  # languages
  - 'lua'
  - 'python'
  # filebrowser
  - 'nnn'
  - 'fzf'
  # needed to compress after garbage collection
  - 'squashfs'
  # drawing
  - 'gnuplot'
  views:
    editors:
      link: roots
      uenv:
        add_compilers: false
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
