ascent:
  compiler:
  - toolchain: gcc
    spec: gcc@12.3
  mpi:
    spec: cray-mpich@8.1.30
    gpu: cuda
  unify: true
  specs:
  - cuda@12.4
  - py-numpy
  - ascent +python
  - ascent -cuda +python
  # - ascent ^cray-mpich +python +cuda cuda_arch=90
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90
  views:
    develop:
      link: roots
      exclude: ["ascent"]
    ascent_cpu:
      link: roots
      exclude: ["ascent+cuda"]
    ascent_gpu:
      link: roots
