ascent:
  compiler:
  - toolchain: gcc
    spec: gcc@12.3
  mpi:
    spec: cray-mpich@8.1.30
    gpu: cuda
  unify: true
  specs:
  - cuda@12.4
  # cuda:
  # - ascent@develop +python ^cray-mpich+cuda ^hdf5@1.14.5+cxx+hl+fortran
  - ascent@develop +python +cuda cuda_arch=90 +vtkh ^raja+cuda ^cray-mpich+cuda ^hdf5@1.14.5+cxx+hl+fortran ^vtk-m +cuda cuda_arch=90  
  # no cuda:
  # - ascent@develop -cuda +python  
  - py-numpy@1.26.4
  # - hdf5 +cxx +hl +fortran
  # - ascent ^cray-mpich +python +cuda cuda_arch=90
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90
  views:
    develop:
      link: roots
      exclude: ["ascent", "ascent-cuda"]
    ascent_cpu:
      link: roots
      exclude: ["ascent+cuda"]
    ascent_gpu:
      link: roots
