ascent:
  compiler:
  - toolchain: gcc
    spec: gcc@12
  mpi:
    spec: cray-mpich@9.0.0
    gpu: cuda
  unify: true
  specs:
  - cmake
  - cuda@12.4  # vtk-m will build with cuda/12.6 but will fail at runtime
  - py-numpy
  - ascent@git.4da1379602c44f72d587a1c7efa8856197ae87df=develop +python +occa +mfem ^conduit@0.9.3
  - raja +cuda
  - umpire +cuda
  - vtk-m +cuda
  variants:
  - +mpi
  - cuda_arch=90
  views:
    default:
      link: roots
