ascent:
  compiler:
  - toolchain: gcc
    spec: gcc@12
  mpi:
    spec: cray-mpich@8.1.30
    gpu: Null
  unify: true
  specs:
  - cmake
  - py-numpy
  - ascent ~cuda +python +occa +mfem
  variants:
  - +mpi
  views:
    default:
    develop:
      link: roots
      exclude: ["ascent"]
