cp2k-mc-scalapack:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - intel-oneapi-mkl +cluster
  - fftw@3.3.10 +openmp
  - libxc
  - sirius@7.4.3 +fortran +scalapack
  - dbcsr@2.6.0 +shared +openmp ^intel-oneapi-mkl ^cray-mpich
  - cosma@2.6.6 +scalapack +shared ^intel-oneapi-mkl ^cray-mpich
  - cp2k@2023.2 +libxc +libint +spglib +cosma +sirius ~elpa build_system=cmake ^intel-oneapi-mkl ^cray-mpich
  variants:
    - +mpi
    - ~cuda
    - ~rocm
    - build_type=Release
  views:
    cp2k-scalapack-dev:
      exclude: ["cp2k"]
    cp2k-scalapack:
      exclude: [""]
  mpi:
    spec: cray-mpich
    gpu: null
cp2k-mc-elpa:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - intel-oneapi-mkl +cluster
  - fftw@3.3.10 +openmp
  - libxc
  - sirius@7.4.3 +fortran + scalapack +elpa
  - dbcsr@2.6.0 +shared +openmp ^intel-oneapi-mkl ^cray-mpich
  - cosma@2.6.6 +scalapack +shared ^intel-oneapi-mkl ^cray-mpich
  - cp2k@2023.2 +libxc +libint +spglib +cosma +sirius +elpa build_system=cmake ^intel-oneapi-mkl ^cray-mpich
  variants:
    - +mpi
    - ~cuda
    - ~rocm
    - build_type=Release
  views:
    cp2k-elpa-dev:
      exclude: ["cp2k"]
    cp2k-elpa:
      exclude: [""]
  mpi:
    spec: cray-mpich
    gpu: null
tools:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - cmake@3.25.2
  - pkgconfig
  - python@3.10
  - py-numpy
