nvhpc-env:
  compiler:
    - toolchain: llvm
      spec: nvhpc@22.11
    - toolchain: gcc
      spec: gcc@11
  mpi:
    spec: cray-mpich
    gpu: null
  unify: true
  specs:
  - cmake%gcc
  - cuda@11.8
  - fftw
  - openblas
  - libxc@5.2.3%nvhpc~cuda
  - quantum-espresso@7.1 %nvhpc +libxc +cuda ~scalapack ^openblas threads=openmp ^libxc
  - patchelf%gcc
  variants:
  - +mpi
  - +cuda
  - cuda_arch=80
  packages:
  - gmake
  - m4
  - perl
  - git
  - pkgconf
  - readline
  - ncurses
  - diffutils
  - libiconv
  - openssl
  - sqlite
  - tar
  - libxml2
  - gettext
  views:
    default:
    develop:
      exclude: ['quantum-espresso']
