nvhpc-env:
  compiler:
    - toolchain: llvm
      spec: nvhpc@22.11
    - toolchain: gcc
      spec: gcc@11
  mpi:
    spec: cray-mpich
    gpu: null
  unify: true
  specs:
  # TODO: don't we pick up the system git?
  # if not, look at adding a packages.yaml file to the recipe
  #- git%gcc
  # TODO: are there any other dependencies that we want to
  # explicitly list here so that:
  #   - modules are generated for developers who use modules
  #   - we can have stricter control over versions
  - cmake%gcc
  - gmake%gcc
  - libxc@5.2.3%nvhpc~cuda
  - cuda@11.8
  - patchelf%gcc
  - quantum-espresso@7.1 %nvhpc +libxc +cuda ~scalapack ^openblas threads=openmp ^libxc
  variants:
  - +mpi
  - +cuda
  - cuda_arch=80
  packages:
  - perl
  - git
  - pkgconf
  - readline
  - ncurses
  - diffutils
  - libiconv
  - openssl
  - sqlite
  - tar
  - libxml2
  - gettext
  views:
    default:
    develop:
      exclude: ['quantum-espresso']
