gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc
  mpi:
      spec: cray-mpich@8.1.29
      gpu: cuda
  unify: true
  specs:
  - cmake
  - cuda@12.4
  - python@3.11
  - py-mpi4py
  - py-h5py
  - py-numpy
  - py-pybind11
  - py-pip
  - py-pyyaml
  - py-scipy
  - py-voluptuous
  - libxc@5.2.3 ~cuda
  - sirius@7.5 +python +tests +fortran +cuda +scalapack ^openblas
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90
  views:
    default:
  packages:
  - git
  - perl

