pv-egl-cuda: 
  compiler:
      - toolchain: gcc
        spec: gcc
  mpi:
      spec: cray-mpich@8.1.28
      gpu: cuda
  unify: true
  specs:
  # Build tools
  - git-lfs
  - cmake
  - ninja
  - direnv
  - ninja
  - libtree
  - llvm@14 ~gold ~cuda
  # maths
  - blaspp
  - eigen
  - fftw
  - lapackpp
  - openblas
  - proj
  # c++ helperrs
  - fmt
  - stdexec@main
  - boost +atomic +chrono +container +context +coroutine +date_time +filesystem +graph +json +mpi +multithreaded +program_options +regex +serialization +shared +system +test +thread
  # IO and parallelism
  - hdf5 +mpi +cxx +hl +threadsafe +shared ~java
  - netcdf-c +mpi
  - h5hut@master
  - lz4
  # cuda
  - cuda@12.3
  # memory management
  - jemalloc
  - mimalloc
  # system
  - numactl
  # profiling/testing
  - gperftools
  - googletest
  # multithreading
  - tbb
  # in-situ support
  - libcatalyst +mpi
  # vtk external deps 
  - cgns@4.4.0
  - double-conversion@3.3.0
  - gl2ps
  - glew
  - jpeg
  - jsoncpp
  - libharu
  - libtiff
  - nlohmann-json
  - libtheora@master
  - pugixml
    # protobuf@3.4 - 3.21 to prevent abseil being pulled in @3.22:
  - protobuf@:3.21 
  - seacas
  - utf8cpp
  # python
  - python@3.11
  - py-pandas
  - py-matplotlib
  - py-mpi4py
  #- vtk-m@2.1.0 +cuda cuda_arch=90 
  #- vtk@master +egl +mpi +opengl2 +python +cuda
  # paraview@master +vtk +mpi +opengl2 +egl +catalyst ~raytracing +python use_vtkm=off +development_files build_edition=rendering 

    #- openimagedenoise@master
    #- ispc@main
    #  - ospray
  variants:
  - build_type=Release
  - +mpi
  - +cuda
  - gl=egl
  - cuda_arch=90
  - ~fortran
  - ~x11
  - ~examples
  views:
    default:
      link: roots

# pv-osmesa:
#   compiler:
#       - toolchain: gcc
#         spec: gcc
#   mpi:
#       spec: cray-mpich@8.1.28
#       gpu: cuda
#   unify: true
#   specs:
#   - cmake
#   - ninja
#   - direnv
#   - fftw
#   - fmt
#   - stdexec  
#   - boost +atomic +chrono +container +context +coroutine +date_time +filesystem +graph +json +mpi +multithreaded +program_options +regex +serialization +shared +system +test +thread
#   - hdf5 +mpi
#   - h5hut@master
#   - ninja
#   - llvm@14 ~gold ~cuda
#   - openblas
#   - blaspp
#   - lapackpp
#   - python@3.11
#   - cuda@12.3
#   - py-pandas
#   - py-matplotlib
#   - tbb
#   - libtheora@master
#   - vtk-m@2.1.0 +cuda cuda_arch=90 
#   - vtk@master +egl +mpi +opengl2 +python +cuda
#   - paraview@master +vtk +mpi +opengl2 +osmesa +tbb +raytracing +python use_vtkm=on +development_files build_edition=rendering 

#     #- openimagedenoise@master
#     #- ispc@main
#     #  - ospray
#     #  We turn off hdf5 because vtk::hdf5 needs the internal hdf5 not the external one
#   variants:
#   - +mpi
#   - +cuda
#   - cuda_arch=90
#   - ~fortran
#   - build_type=Release
#   - cxxstd=20
#   - ~examples
#   views:
#     default:
 
