#!/bin/bash

set -u
set -e

VIEW_ROOT={{ env.mount }}/env/develop
LIBRARY_PATH=${VIEW_ROOT}/lib:${VIEW_ROOT}/lib64:$LIBRARY_PATH

# === DOWNLOAD VMD SOURCEs
vmd_name="vmd-1.9.4a57"
vmd_tarball="${vmd_name}.src.tar.gz"
vmd_tarball_filepath={{ env.build }}/environments/${vmd_tarball}
curl --user $CSCS_REGISTRY_USERNAME:$CSCS_REGISTRY_PASSWORD https://jfrog.svc.cscs.ch/artifactory/uenv-sources/vmd/${vmd_tarball} --output ${vmd_tarball_filepath}

tar xf ${vmd_tarball_filepath}

# === BUILD PLUGINS
PLUGINDIR={{ env.mount }}/plugins

pushd plugins
gmake LINUXARM64
gmake distrib
popd

# === BUILD VMD
pushd ${vmd_name}
ln -s $PLUGINDIR .

export TCL_INCLUDE_DIR=${VIEW_ROOT}/include
export TCL_LIBRARY_DIR=${VIEW_ROOT}/lib
export TK_INCLUDE_DIR=${VIEW_ROOT}/include
export TK_LIBRARY_DIR=${VIEW_ROOT}/lib

VMD_ROOT={{ env.mount }}/vmd
export VMDINSTALLBINDIR=$VMD_ROOT/bin
export VMDINSTALLLIBRARYDIR=$VMD_ROOT/lib/vmd

patch configure << 'EOF'
--- configure   2025-02-21 12:14:19.000000000 +0100
+++ configure   2025-02-21 12:15:38.000000000 +0100
@@ -2629,10 +2629,9 @@
   if ($config_tk) { $tcl_libs = "-ltk8.5 -lX11 " . $tcl_libs; }
   $vmd_libs          = "$tcl_libs -lz";

-  $arch_nvcc     = "/usr/local/cuda/bin/nvcc";
+  $arch_nvcc     = "nvcc";
   $arch_nvccflags   = "--ptxas-options=-v " .
-                    "-gencode arch=compute_30,code=compute_30 " .
-                    "-gencode arch=compute_70,code=compute_70 " .
+                    "-gencode arch=compute_90,code=compute_90 " .
                     "--ftz=true ";
   $cuda_library     = "-L/usr/local/cuda/lib64";
   $arch_cc       = "cc";
EOF

./configure LINUXARM64 TCL GCC CUDA FLTK FLTKOPENGL EGLPBUFFER PTHREADS SHARED NOSTATICPLUGINS LIBPNG ZLIB

cd src && make -j40 && make install
ln -s $VMD_ROOT/lib/vmd/vmd.so $VMD_ROOT/lib/vmd/vmd_LINUXARM64
popd

cat << EOF > activate.sh
export LD_LIBRARY_PATH=${VIEW_ROOT}/lib:${VIEW_ROOT}/lib64:$LD_LIBRARY_PATH
export PLUGINDIR=$PLUGINDIR
export PATH=${VMD_ROOT}/bin:$PATH
EOF
