name: prgenv-gnu
spack:
  repo: https://github.com/spack/spack.git
  commit: c702f5b89eea1950c76472fbf8f0919ad12880a6
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: 0c1f599673edfaaa9ca53720f2d4a281d0f7d63d
store: /user-environment
description: GNU Compiler toolchain with cray-mpich, Python, CMake and other development tools.
version: 2
