gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc@12
  mpi:
      spec: cray-mpich
      gpu: Null
  unify: true
  specs:
  - cmake
  - fftw
  - fmt
  - hdf5
  - ninja@1.11
  - openblas
  - python@3.11
  - py-pybind11
  - osu-micro-benchmarks@5.9
  variants:
  - +mpi
  views:
    default:
