gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc@12
  mpi:
      spec: cray-mpich
      gpu: Null
  unify: true
  specs:
  - cmake
  - ninja@1.11
  - osu-micro-benchmarks@5.9
  - python@3.11
  variants:
  - +mpi
