# NB. git sha for spack is required for some vtk external packages, but newer sha breaks other stuff
name: ParaView
store: /user-environment
spack:
  commit: 195b869e1c5f0f850fe16ca1cc0c77fc71f5fcd6
  repo: https://github.com/spack/spack.git
description: ParaView for eiger using osmesa
modules: false
