cp2k:
  compiler:
  - toolchain: gcc
    spec: gcc@12.3
  unify: true
  specs:
  - cmake@3.27.9
  - ninja@1.11.1
  - cuda@12.2 # Can't be newer than driver version, for DBCSR
  - openblas@0.3.26 threads=openmp
  - netlib-scalapack@2.2.0
  - fftw@3.3.10
  - libxc@6.2.2 ~cuda
  - libint@2.6.0 +fortran tune=cp2k-lmax-5
  - spglib@2.3.1
  - cosma@2.6.6 +gpu_direct +scalapack +shared ^cray-mpich
  - spla@1.5.5 +fortran ^cray-mpich
  - elpa ^cray-mpich
  - sirius@7.5.2 +fortran +scalapack +elpa ~apps ^cray-mpich
  # cuda_arch=90 not yet supported by DBCSR and CP2K
  - dbcsr@2.6.0 smm=blas +shared +cuda cuda_arch=80 ^cray-mpich
  - cp2k@2024.1 +libxc +libint +spglib +cosma +spla +elpa +sirius lmax=5 +cuda cuda_arch=80 build_system=cmake ^cray-mpich
  variants:
    - +mpi
    - +openmp
    - +cuda
    - cuda_arch=90
    - build_type=Release
  mpi:
    spec: cray-mpich
    gpu: cuda
  views:
    develop:
      link: roots
      exclude: ["cp2k"]
    cp2k:
      link: roots
