name: prgenv-gnu
spack:
  repo: https://github.com/spack/spack.git
  commit: v1.1.1
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: afdf167333306c0a018739a1b27652b5f44d7304 # develop on 2026-03-11
store: /user-environment
description: GNU Compiler toolchain with cray-mpich, Python, CMake and other development tools.
version: 2
