name: quantumespresso
version: 2
spack:
  commit: 6b82a5593fad7fdfa9f9a9ef3f20248d5a95a675 # develop June 2
  repo: https://github.com/spack/spack.git
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: badd2122140f3850ac5e57a7ece1e885cc1436ce
store: /user-environment
description: QuantumESPRESSO on GH200
