name: ascent
store: /user-tools
description: "Ascent in-situ visualization library"
spack:
  repo: https://github.com/spack/spack.git
  commit: releases/v1.1
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: 53f15337d68d9b1d7fa87eecfa393fe591d3496a # add ascent catalyst support
version: 2
