gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc@11
  mpi:
      spec: cray-mpich
      gpu: cuda
  unify: true
  specs:
  - cmake
  - cuda@11.8
  - python@3.11
  - py-mpi4py
  - py-h5py
  - py-numpy
  - py-pybind11
  - py-pip
  - py-pyyaml
  - py-scipy
  - py-voluptuous
  - libxc@5.2.3 ~cuda
  - sirius@7.5 +python +tests +fortran +cuda +scalapack +elpa ^elpa+cuda ^intel-oneapi-mkl+cluster
  variants:
  - +mpi
  - +cuda
  - cuda_arch=80
  views:
    default:
  packages:
  - git
  - perl

