#!/bin/bash

#forge_bin=$(spack -C {{ env.config }} location -i linaro-forge)/bin
#ln -s $forge_bin {{ env.mount }}/bin
forge_bin={{ env.mount }}/env/forge/bin
echo "export PATH=$forge_bin:$PATH" >> {{ env.mount }}/activate
echo "export UENV_DDT_VERSION=23.1.2" >> {{ env.mount }}/activate
