name: icon-a100
store: /user-environment
spack:
  commit: releases/v0.20
  repo: https://github.com/spack/spack.git
description: The tools required to build ICON with OpenACC+Fortran on NVIDIA A100 GPUs
