clusters:
  eiger:
    uarch: [zen2]
    partition: [normal]
    runner: f7s
  clariden:
    uarch: [a100, mi200]
    partition: [nvgpu, amdgpu]
    runner:
      slurm-tag: clariden-spack-stack-builder
      baremetal-tag: clariden-login-baremetal
uenvs:
  gromacs:
    "2023":
      recipes:
        # zen2 and zen3 targets use the same recipe
        zen2: 2023/mc
        zen3: 2023/mc
        a100: 2023/a100
      deploy:
        # deploy to both the production and test clusters
        eiger: [zen2]
        clariden: [a100]
