name: prgenv-gnu
version: 2
spack:
  commit: releases/v1.0
  repo: https://github.com/spack/spack.git
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: 43bfc49ab9d32bdfdd1984848b15793b4072ece2 
store: /user-environment
description: GNU Compiler toolchain with cray-mpich, Python, CMake and other development tools for MI300A
