nvhpc-env:
  compiler:
    - toolchain: gcc
      spec: gcc@11
  mpi:
    spec: cray-mpich
    gpu: null
  unify: true
  specs:
  - cmake
  - fftw
  - openblas
  - libxc@5.2.3
  - quantum-espresso@7.1 %gcc +libxc +scalapack +openmp ^openblas threads=openmp ^libxc
  - patchelf
  variants:
  - +mpi
  packages:
  - gmake
  - m4
  - perl
  - git
  - pkgconf
  - readline
  - ncurses
  - diffutils
  - libiconv
  - openssl
  - sqlite
  - tar
  - libxml2
  - gettext
  views:
    default:
    develop:
      exclude: ['quantum-espresso']
