scorep:
  compiler:
  - toolchain: gcc
    spec: gcc@12
  unify: when_possible
  mpi:
    spec: cray-mpich@9.0.0
    gpu: Null
  specs:
  - scorep@9.0.rc2 +papi +gotcha +unwind ^libunwind ^binutils +libiberty
  # uenv build scorep/9.0.rc2/mc score/9.0.rc2@eiger%zen2
#del  ./configure --prefix=/capstor/store/cscs/cscs/csstaff/piccinal/SPACK/spack.git.eiger/DEL/install \
#del --with-otf2 \
#del --with-opari2 \
#del --with-cubew \
#del --with-cubelib \
#del --with-libunwind-include=$P3/include \
#del --with-libunwind-lib=$P3/lib \
#del --with-libbfd-include=$P2/include \
#del --with-libbfd-lib=$P2/lib \
#del --with-libgotcha=download
#del 
  variants:
    - +mpi
    - ~cuda
#del     - +openmp
#del     - ~rocm
  views:
    scorep:
      link: roots
    develop:
      link: roots
      exclude: ["scorep"]
