name: insitu
store: /user-environment
description: ascent@0.9.4 on GH200
spack:
  repo: https://github.com/spack/spack.git
  commit: 73eaea13f381e3495299284856fd02a64e1d154c
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: 4b8bb3514838ce9e8bbc2ca7f98e62dbd7100c63
modules: True
version: 2
