name: prgenv-nvfortran
spack:
  repo: https://github.com/spack/spack.git
  commit: releases/v1.2
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: 2fb6197c7eb7b9cfd9089d089a8460a96eaab46d # 15. July 26
store: /user-environment
description: NVIDIA compiler toolchain (nvhpc) with cray-mpich, Python, CMake and other development tools.
version: 2
