zen-gcc:
  compiler:
      - toolchain: gcc
        spec: gcc@11
  mpi:
      spec: cray-mpich
      gpu: null
  unify: true
  specs:
  - osu-micro-benchmarks@5.9
  - babelstream +omp
  packages:
  - perl
  - diffutils
  - gettext
cuda-gcc:
  compiler:
      - toolchain: gcc
        spec: gcc@11
  mpi:
      spec: cray-mpich
      gpu: cuda
  unify: true
  specs:
  - osu-micro-benchmarks@5.9
  - babelstream
  packages:
  - perl
  - diffutils
  - gettext
  variants:
  - cuda_arch=80
  - +mpi
  - +cuda
