name: paraview-jb-dev
store: /user-environment
description: ParaView visualization tool

spack:
  commit: releases/v0.19
  repo: https://github.com/spack/spack.git

mirror:
  enable: true
  key: /tmp/gpg-spack-paraview
