name: prgenv-gnu
spack:
  repo: https://github.com/spack/spack.git
  commit: releases/v1.1
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: v2026.03.0
store: /user-environment
description: GNU Compiler toolchain with cray-mpich, Python, CMake and other development tools.
version: 2
