version: 3
name: paraview
store: /user-environment
spack:
  repo: https://github.com/spack/spack.git
  commit: releases/v1.2
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: releases/v2026.06
description: ParaView for Alps Zen2 clusters using OSMesa (Off Screen Mesa)
default-view: default
