scorep:
  compiler:
  - toolchain: gcc
    spec: gcc@12
  unify: when_possible
  mpi:
    spec: cray-mpich@9.0.0
    gpu: cuda
  specs:
  - cmake
  - hdf5 +cxx +hl ~fortran
  - scalasca@2.6.2 ^scorep@9.0 +cuda +mpi ~papi +gotcha +unwind ^libunwind ^binutils +libiberty ^cuda@12
  views:
    default:
      link: roots
