lammps:
  compiler:
  - toolchain: gcc
    spec: gcc@12
  mpi:
    spec: mpich
    gpu: cuda
  unify: true
  specs:
  - cuda@12
  - kokkos-nvcc-wrapper@4.1.00
  - kokkos@4.1.00 +wrapper
  - lammps
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90
  - +kokkos
  views:
    default:
        link: run
  packages:
   - perl
