amber-env:
  compiler: [gcc]
  network:
      mpi: cray-mpich@8.1.32 +cuda
  unify: true
  specs:
  - boost +chrono +filesystem +iostreams +mpi +program_options +python +regex +serialization +shared +system +timer
  - cmake
  - cuda@12.8
  - fftw
  - gsl
  - hdf5+cxx+hl+fortran
  - netlib-scalapack
  - libtree
  - netcdf-c
  - netcdf-cxx
  - netcdf-cxx4
  - netcdf-fortran
  - openblas threads=openmp
  - osu-micro-benchmarks ~xccl
  # amber requires tikinter
  - python +tkinter
  - zlib-ng
  - xcb-util-cursor
  # python packages
  - py-biopython
  - py-pip  # used to install freesasa in post-install
  - py-numpy
  - py-scipy
  - py-matplotlib
  - py-setuptools
  - py-pandas
  - py-numba
  - py-gemmi
  - py-rich
  - py-scikit-learn
  - py-sympy
  - py-pydantic
  - py-psutil
  - py-networkx
  # installed using pip in post-install
  #- freesasa
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90a
  views:
    amber:
      # include all runtime deps in view so that all python packages are available
      link: run
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
