mirror:
  enable: true
  key: /scratch/e1000/bcumming/uenv-cache/push-key.gpg
name: arbor-cpu
spack:
  commit: v0.19.0
  repo: https://github.com/spack/spack.git
store: /user-environment
system: hohgant

