name: prgenv-gnu
spack:
  commit: 2f389f7578b4eba0ab278b8d79410b62dd5d69d5 # spack develop from 2025-05-22 + kokkos-kernels language dep
  repo: https://github.com/msimberg/spack.git
store: /user-environment
description: GNU Compiler toolchain with cray-mpich, Python, CMake and other development tools.

