# environments.yaml
gcc-amdgpu:
  views:
    default:
  compiler:
      - toolchain: gcc
        spec: gcc@12
  unify: true
  specs:
  - cmake@3.24.4
  - hdf5
  - hip@5.3
  - hipify-clang
  - hipcub
  - rocblas
  - rocfft
  - rocprim
  - rocsolver
  - rocthrust
  variants:
  - amdgpu_target=gfx90a
  - +mpi
  mpi:
    spec: cray-mpich
    gpu: rocm
