paraview-amd-zen2-osmesa:
  compiler:
  - toolchain: gcc
    spec: gcc
  mpi:
    spec: cray-mpich@8.1.30
    gpu: Null
  unify: true
  views:
    default:
      link: roots

  specs:

  # Build tools
  - git-lfs
  - cmake
  - ninja
  - direnv
  - ninja
  - libtree
  - llvm@18 ~gold ~cuda

  # maths
  - blaspp
  - eigen
  - fftw
  - lapackpp
  - openblas
  - proj

  # c++ helpers
  - fmt@10
  - stdexec@main
  - boost +atomic +chrono +container +context +coroutine +date_time +filesystem +graph +json +mpi +multithreaded +program_options +regex +serialization +shared +system +test +thread

  # IO and parallelism
  - hdf5 +mpi +cxx +hl +threadsafe +shared ~java
  - netcdf-c +mpi
  - h5hut@master
  - lz4
  - adios2 +python +hdf5

  # memory management
  - jemalloc
  - mimalloc

  # system
  - numactl

  # profiling/testing
  - gperftools
  - googletest

  # multithreading
  - tbb

  # in-situ support
  - libcatalyst +mpi +python

  # vtk external deps
  - cgns@4.4.0
  - double-conversion@3.3.0
  - gl2ps
  - glew
  - jpeg
  - jsoncpp
  - libharu
  - libtiff
  - nlohmann-json
  - libtheora@master
  - pugixml
  - pegtl
  - protobuf@:3.21
  - seacas ~fortran ~applications ~legacy ~tests ~x11
  - utf8cpp

  # c2sm
  # - libcdi-pio
  - cdi

  # python
  - python@3.11
  - py-numpy
  - py-pandas
  - py-matplotlib
  - py-mpi4py
  - py-cftime

  # raytracing in VTK/ParaView
  - ospray@3.1 ~mpi +denoiser +volumes ~apps ~glm
  - ispc@main
  - openvkl
  - embree
  - rkcommon
  - openimagedenoise

  # offscreen rendering
  - mesa         +osmesa
  - osmesa ^mesa +osmesa
  - glew ^[virtuals=gl] osmesa ^mesa +osmesa

  variants:
  - ~cuda
  - ^[virtuals=gl] osmesa ^mesa +osmesa
  - build_type=Release
  - cxxstd=17
  - +mpi
  - ~fortran
  - ~x11
  - ~examples
  - ~tests
