#!/usr/bin/env bash

oras_version=1.1.0
oras_file=oras_${oras_version}_linux_amd64.tar.gz
oras_url=https://github.com/oras-project/oras/releases/download/v${oras_version}/${oras_file}

log "download and install oras $oras_url"

oras_path=`mktemp -d`

(cd "$oras_path"; wget --quiet "$oras_url"; tar -xzf $oras_file; rm *.tar.gz)

export PATH="$oras_path:$PATH"
log "oras v${oras_version} installed in ${oras_path}"

# Obtain credentials for JFrog - required to push the image and meta-data
creds_json=$(curl --retry 5 --retry-connrefused --fail --silent "$CSCS_CI_MW_URL/credentials?token=$CI_JOB_TOKEN&creds=container_registry")
oras_creds="$(echo ${creds_json} | jq --join-output '"--username " + .container_registry.username + " --password " +.container_registry.password')"

jfrog_u="$(echo ${creds_json} | jq -r '.container_registry.username')"
jfrog_p="$(echo ${creds_json} | jq -r '.container_registry.password')"

log "log in to jfrog.svc.cscs.ch with oras"

# Create a unique credentials path for this job,
# because by default credentials are stored in ~/.docker/config.json which
# causes conflicts for concurrent jobs.
jfrog_creds_path="${oras_path}/docker/config.json"
log "jfrog credentials to be stored in $jfrog_creds_path"

echo ${jfrog_p} | oras login --registry-config ${jfrog_creds_path}  jfrog.svc.cscs.ch --username "${jfrog_u}" --password-stdin
[[ $? -eq 0  ]] || err "failed oras login to JFrog - can't push image to uenv registry"

