name: ParaView
store: /user-environment
spack:
  commit: 4f0e336ed09408809df1b570422a64b3e02e9eb2
  repo: https://github.com/spack/spack.git
description: ParaView for eiger using osmesa
modules: false
