lammps:
  compiler:
      - toolchain: gcc
        spec: gcc@11
  mpi:
      spec: cray-mpich
      gpu: cuda
  unify: when_possible
  specs:
  - cmake
  - cuda@11.8
  - lammps@20230328 +cuda
  - lammps@20230328 +plumed +cuda
  - hwloc
  - python@3.10
  - vtk
  - kokkos
  - blas
  - lapack
  - fftw-api
  variants:
  - +mpi
  - +cuda
  - cuda_arch=80
  views:
    develop:
      exclude: ['lammps']
    lammps:
      exclude: ['lammps+plumed']
      link: run
    plumed:
      link: run
  packages:
   - perl
  

