cp2k-nvgpu:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - cuda@11.8
  - intel-oneapi-mkl +cluster
  - fftw@3.3.10 +openmp
  - libxc ~cuda
  - sirius +fortran +scalapack
  - dbcsr@develop +cuda cuda_arch=70 +shared +openmp ^intel-oneapi-mkl ^cray-mpich
  - cosma@master +gpu_direct +scalapack +shared ^intel-oneapi-mkl ^cray-mpich
  - cp2k@master +libxc +libint +spglib +cosma +sirius ~elpa build_system=cmake ^intel-oneapi-mkl ^cray-mpich
  variants:
    - +mpi
    - +cuda
    - cuda_arch=80
    - build_type=Release
  views:
    dev:
      exclude: ["cp2k"]
    scalapack:
      exclude: [""]
  mpi:
    spec: cray-mpich
    gpu: cuda
cp2k-nvgpu-elpa:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - cuda@11.8
  - intel-oneapi-mkl +cluster
  - fftw@3.3.10 +openmp
  - libxc ~cuda
  - sirius +fortran + scalapack +elpa
  - dbcsr@develop +cuda cuda_arch=70 +shared +openmp ^intel-oneapi-mkl ^cray-mpich
  - cosma@master +gpu_direct +scalapack +shared ^intel-oneapi-mkl ^cray-mpich
  - cp2k@master +libxc +libint +spglib +cosma +sirius +elpa build_system=cmake ^intel-oneapi-mkl ^cray-mpich
  variants:
    - +mpi
    - +cuda
    - cuda_arch=80
    - build_type=Release
  views:
    dev-elpa:
      exclude: ["cp2k"]
    elpa:
      exclude: [""]
  mpi:
    spec: cray-mpich
    gpu: cuda
tools:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - cmake@3.25.2
  - pkgconfig
  - python@3.10
  - py-numpy
