name: opencode
store: /user-tools
spack:
  repo: https://github.com/spack/spack.git
  commit: v1.2.2
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: 7318c6ac1a452a5e9f433d6de81841a036114e8f # 21 August 26
description: "Opencode and Bubble-wrapped opencode"
default-view: opencode
version: 3
