stages:
  - configure
  - run

pipeline-configure:
  stage: configure
  tags: [clariden-login-baremetal]
  script:
    - ./ci/configure-pipeline
  artifacts:
    paths:
      - pipeline.yml

generated-pipeline:
  stage: run
  needs: [pipeline-configure]
  trigger:
    include:
      - artifact: pipeline.yml
        job: pipeline-configure
    forward:
      pipeline_variables: true
    strategy: depend
