stages:
  - configure
  - run

pipeline-configure:
  stage: configure
  tags: [rosa-k8s-lightweight]
  image: docker.io/python:latest
  script:
    - ./workflow/pipeline/configure-pipeline -c./config.yaml -r./recipes -s$system -u$uenv -a$uarch -o./pipeline.yml
  artifacts:
    paths:
      - pipeline.yml

generated-pipeline:
  stage: run
  needs: [pipeline-configure]
  variables:
    CSCS_NOTIFICATION_CONTEXT:  "$system-$uarch-$uenv"
  trigger:
    include:
      - artifact: pipeline.yml
        job: pipeline-configure
    forward:
      pipeline_variables: true
    strategy: depend
