stages:
  - configure
  - run

pipeline-configure:
  stage: configure
  tags: [clariden-login-baremetal]
  script:
    - ./config/configure.sh
  variables:
    CSCS_NOTIFICATION_CONTEXT: "configure"
  artifacts:
    paths:
      - pipeline.yml

child-pipeline:
  stage: run
  variables:
    CSCS_CI_MW_URL: $CSCS_CI_MW_URL
  trigger:
    include:
      - artifact: pipeline.yml
        job: pipeline-configure
    strategy: depend
