stages:
  - configure
  - run

pipeline-configure:
  stage: configure
  tags: [clariden-login-baremetal]
  script:
    - printenv | grep CI_MERGE
    - ./ci/configure-pipeline
  artifacts:
    paths:
      - pipeline.yml

generated-pipeline:
  stage: run
  needs: [pipeline-configure]
  variables:
    CSCS_CI_MW_URL: $CSCS_CI_MW_URL
  trigger:
    include:
      - artifact: pipeline.yml
        job: pipeline-configure
    strategy: depend
