stages:
  - configure
  - run

pipeline-configure:
  stage: configure
  tags: [languard-k8s-lightweight]
  image: docker.io/python:latest
  script:
    - echo "CI_PROJECT_DIR=$CI_PROJECT_DIR"
    - git clone https://github.com/eth-cscs/uenv-pipeline.git
    - ./uenv-pipeline/configure-pipeline -c./config.yaml -r./recipes -s$system -u$uenv -a$uarch -o./pipeline.yml
    - sed -i -e 's|./uenv-pipeline/stage-build|echo CI_PROJECT_DIR=$CI_PROJECT_DIR|' ./pipeline.yml
  artifacts:
    paths:
      - pipeline.yml
      - uenv-pipeline

generated-pipeline:
  stage: run
  needs: [pipeline-configure]
  variables:
    CSCS_NOTIFICATION_CONTEXT:  "$system-$uarch-$uenv"
    PARENT_PIPELINE_ID: "$CI_PIPELINE_ID"
  trigger:
    include:
      - artifact: pipeline.yml
        job: pipeline-configure
    forward:
      pipeline_variables: true
    strategy: depend
