stages:
  - configure
  - run

pipeline-configure:
  stage: configure
  tags: [clariden-login-baremetal]
  script:
    - ./config/configure.sh
  artifacts:
    paths:
      - pipeline.yml

child-pipeline:
  stage: run
  trigger:
    include:
      - artifact: pipeline.yml
        job: pipeline-configure
