stages:
  - build
  - test

.stack-build:
  stage: build
  variables:
    SLURM_TIMELIMIT: 180
  script:
  - ./stack-build -n $STACK_NAME -s $STACK_SYSTEM -r $STACK_RECIPE -b /dev/shm/jenkssl
  after_script:
  - rm -Rf /dev/shm/jenkssl
  artifacts:
    paths:
    - artifacts/

.run-reframe:
  stage: test
  variables:
    SLURM_TIMELIMIT: 30
  variables:
    GIT_STRATEGY: fetch
  script:
  - ./run-reframe -n $STACK_NAME -s $STACK_SYSTEM
  artifacts:
    when: always
    paths:
    - reframe/report.xml
    reports:
      junit: reframe/report.xml

#
# HOHGANT
#

.stack-build-hohgant:
  extends: .stack-build
  tags: [hohgant-spack-stack-builder]
  variables:
    STACK_SYSTEM: hohgant
.stack-build-hohgant-cpu:
  extends: .stack-build-hohgant
  variables:
    SLURM_PARTITION: cpu
.stack-build-hohgant-a100:
  extends: .stack-build-hohgant
  variables:
    SLURM_PARTITION: nvgpu

.run-reframe-hohgant:
  extends: .run-reframe
  tags: ['hohgant-login-baremetal']
  variables:
    STACK_SYSTEM: hohgant
.run-reframe-hohgant-cpu:
  extends: .run-reframe-hohgant
  variables:
    SLURM_PARTITION: cpu
.run-reframe-hohgant-a100:
  extends: .run-reframe-hohgant
  variables:
    SLURM_PARTITION: nvgpu

#
# CLARIDEN
#

.stack-build-clariden:
  extends: .stack-build
  tags: [clariden-spack-stack-builder]
  variables:
    STACK_SYSTEM: clariden
.stack-build-clariden-a100:
  extends: .stack-build-clariden
  variables:
    SLURM_PARTITION: nvgpu

.run-reframe-clariden:
  extends: .run-reframe
  tags: ['clariden-login-baremetal']
  variables:
    STACK_SYSTEM: clariden
.run-reframe-clariden-a100:
  extends: .run-reframe-clariden
  variables:
    SLURM_PARTITION: nvgpu
