stages:
  - build

.stack-build:
  stage: build
  variables:
    SLURM_TIMELIMIT: 180
  script:
  - ./stack-build -n $STACK_NAME -s $STACK_SYSTEM -r $STACK_RECIPE -b /dev/shm/jenkssl || cp -r /tmp/jenkssl/spack-stage $CI_PROJECT_DIR/
  after_script:
  - rm -Rf /dev/shm/jenkssl

.stack-build-hohgant:
  extends: .stack-build
  tags: [hohgant-spack-stack-builder]
  variables:
    STACK_SYSTEM: hohgant
.stack-build-hohgant-cpu:
  extends: .stack-build-hohgant
  variables:
    SLURM_PARTITION: cpu
.stack-build-hohgant-a100:
  extends: .stack-build-hohgant
  variables:
    SLURM_PARTITION: nvgpu
.stack-build-hohgant-mi200:
  extends: .stack-build-hohgant
  variables:
    SLURM_PARTITION: amdgpu
