stages:
  - build
  - test

.stack-build:
  stage: build
  variables:
    SLURM_TIMELIMIT: 180
    SPACK_DEVELOP: ""
  script:
  - ./stack-build -n $STACK_NAME -s $STACK_SYSTEM -r $STACK_RECIPE -b /dev/shm/jenkssl $SPACK_DEVELOP
  after_script:
  - rm -Rf /dev/shm/jenkssl
  artifacts:
    paths:
    - artifacts/

.run-reframe:
  stage: test
  tags: [clariden-login-baremetal]
  variables:
    SLURM_TIMELIMIT: 30
  variables:
    GIT_STRATEGY: fetch
  script:
  - ./run-reframe -n $STACK_NAME -s $STACK_SYSTEM
  artifacts:
    when: always
    paths:
    - report.xml
    reports:
      junit: report.xml

.stack-build-clariden:
  extends: .stack-build
  tags: [clariden-spack-stack-builder]
  variables:
    STACK_SYSTEM: clariden
.stack-build-clariden-a100:
  extends: .stack-build-clariden
  variables:
    SLURM_PARTITION: nvgpu
.stack-build-clariden-mi200:
  extends: .stack-build-clariden
  variables:
    SLURM_PARTITION: amdgpu

.run-reframe-clariden:
  extends: .run-reframe
  variables:
    STACK_SYSTEM: clariden
.run-reframe-clariden-a100:
  extends: .run-reframe-clariden
  variables:
    SLURM_PARTITION: nvgpu
.run-reframe-clariden-mi200:
  extends: .run-reframe-clariden
  variables:
    SLURM_PARTITION: amdgpu
