stages:
  - build
  - test

.stack-build:
  stage: build
  variables:
    SLURM_TIMELIMIT: 180
    SPACK_DEVELOP: ""
  script:
  - ./stack-build -n $STACK_NAME -s $STACK_SYSTEM -r $STACK_RECIPE -b /dev/shm/jenkssl $SPACK_DEVELOP
  after_script:
  - rm -Rf /dev/shm/jenkssl
  artifacts:
    paths:
    - artifacts/

.run-reframe:
  stage: test
  tags: ['clariden-login-baremetal']
  variables:
    SLURM_TIMELIMIT: 30
  variables:
    GIT_STRATEGY: fetch
  script:
  - ./run-reframe -n $STACK_NAME -s $STACK_SYSTEM
  artifacts:
    when: always
    paths:
    - report.xml
    reports:
      junit: report.xml

