#!/usr/bin/env bash

usage() {
  echo "Usage: `basename $0` <cmd> [args...]"
  if ! [ -z "$1" ]; then
    echo $1
  fi
  exit 1
}

if [ $# -eq 1 ]; then
  usage
fi

if [ -z ${SLURM_LOCALID-} ]; then
  usage "This wrapper is supposed to be used in a SLURM job."
fi

GPUS=(3 2 1 0)
let lrank=$SLURM_LOCALID%4
export VTK_DEFAULT_EGL_DEVICE_INDEX=${GPUS[lrank]}

exec $*
