arbor:
  compiler:
      - toolchain: gcc
        spec: gcc
  mpi:
      spec: cray-mpich@8.1.28
  unify: true
  specs:
  # build tools
  - python@3.11
  # build tools
  - cmake
  - ninja
  - fmt
  - pugixml
  - nlohmann-json
  - osu-micro-benchmarks
  - random123
  # python packages
  - py-mpi4py
  - py-numpy
  - py-pandas
  - py-pip
  - py-pybind11
  - py-sphinx
  - py-svgwrite
  variants:
  - +mpi
  packages:
  - diffutils
  - gettext
  - gmake
  - libxml2
  - perl
