ascent_nocuda:
  compiler:
  - toolchain: gcc
    spec: gcc@12
  mpi:
    spec: cray-mpich@8.1.30
  unify: true
  specs:
  - cmake
  - py-numpy
  - ascent@git.4da1379602c44f72d587a1c7efa8856197ae87df=develop -cuda +vtkh +python +occa +mfem ^conduit@0.9.3
  - raja -cuda
  - umpire -cuda
  - vtk-m -cuda
  - openblas threads=openmp
  variants:
  - +mpi
  views:
    default:
      link: roots
