# environments.yaml
gcc-amdgpu:
  views:
    default:
  compiler:
      - toolchain: gcc
        spec: gcc@12
  unify: true
  specs:
  - cmake@3.24.4
  - hip@5.4
  - hipify-clang
  - rocthrust amdgpu_target=gfx90a
  - rocprim amdgpu_target=gfx90a
  - hipcub amdgpu_target=gfx90a
  - hdf5 +mpi
  variants:
  - amdgpu_target=gfx90a
  mpi:
    spec: cray-mpich
    gpu: rocm
