gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc@11
  mpi:
      spec: cray-mpich
      gpu: false
  unify: true
  specs:
  - ncview
  - cdo
  - nco
  - ferret
  views:
    default:
  packages:
  - git
  - perl

