prgenv-gcc:
  compiler:
    - toolchain: gcc
      spec: gcc@12
  unify: when_possible
  mpi:
    spec: cray-mpich@8.1.28
  packages:
  - perl
  - curl
  - autoconf
  - m4
  - automake
  - texinfo
  - libtool
  - gawk
  specs:
  - cdo
  - gdal
  - geos
  - gsl
  - hdf5@1.12.2 +fortran +threadsafe ~mpi
  - ncview
  - nco
  - ncl
  - netcdf-c@4.8.1~mpi ^hdf5~mpi api=v18
  - proj
  - python@3.11
  - r@4.2.2
  - udunits
  views:
    climana:
      link: roots
      uenv:
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
