climana:
  compiler:
    - toolchain: gcc
      spec: gcc@12
  unify: when_possible
  mpi:
    spec: cray-mpich@8.1.28
  packages:
  - perl
  - autoconf
  - m4
  - automake
  - texinfo
  - libtool
  - gawk
  - curl
  specs:
  # choose fftw instead of the default intel-oneapi-mkl.
  # this saves ~2GB of space, and reduces image build time.
  - cdo ^[virtuals=fftw-api] fftw
  #- curl
  - fribidi
  - gdal
  - geos
  - gsl
  - harfbuzz
  - hdf5@1.12.2 +fortran +threadsafe ~mpi
  - libpng
  - ncview
  - nco
  - ncl
  - netcdf-c@4.8.1~mpi ^hdf5~mpi api=v18
  - proj
  - python@3.11
  - sqlite
  - r@4.4
  - udunits
  views:
    climana:
      link: roots
      uenv:
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
