cp2k:
  compiler:
  - toolchain: gcc
    spec: gcc@12.3
  unify: true
  specs:
  - cmake
  - ninja
  - openblas threads=openmp
  - netlib-scalapack
  - fftw
  - libxc@7 build_system=cmake
  - spglib
  - spla
  - elpa
  - libxsmm
  - plumed
  # libint
  - libint
  - eigen@3
  # pika
  - pika@0.30.1 malloc=mimalloc
  - mimalloc
  - boost
  - fmt
  - spdlog
  - hwloc
  # DLA-Future
  - dla-future@0.7.3 +scalapack +miniapps
  - blaspp
  - lapackpp
  - dla-future-fortran
  # DFTD4
  - dftd4
  - multicharge
  - mctc-lib
  # COSMA
  - costa
  - cosma
  # SIRIUS
  - hdf5
  - spfft
  - sirius +dlaf +elpa +scalapack
  # CP2K
  - dbcsr@2.8.0
  - cp2k@2025.1 +libxc +libint +spglib +cosma +spla +elpa +dlaf +sirius +plumed +dftd4 lmax=5 build_system=cmake
  variants:
    - +mpi
    - +openmp
    - build_type=Release
    - ~cuda
    - ~rocm
  mpi:
    spec: cray-mpich@8.1.30
  views:
    develop:
      link: roots
      exclude: ["cp2k"]
    cp2k:
      link: roots
