stages:
  - build
  - test


.base-build:
  stage: build
  variables:
    SLURM_TIMELIMIT: 180
  script:
  - ./stack-build -n $STACK_NAME -s $STACK_SYSTEM -r $STACK_RECIPE -b /dev/shm/jenkssl $SPACK_DEVELOP
  after_script:
  - rm -Rf /dev/shm/jenkssl
  artifacts:
    paths:
    - artifacts/


.base-test:
  stage: test
  variables:
    SLURM_TIMELIMIT: 30
    GIT_STRATEGY: fetch
  script:
  - ./run-reframe -n $STACK_NAME -s $STACK_SYSTEM
  artifacts:
    when: always
    paths:
    - report.xml
    reports:
      junit: report.xml


{% for job in jobs %}

build-{{job.uenv}}/{{job.version}}-{{job.system}}/{{job.uarch}}:
  extends: .base-build
  tags: ["{{job.slurm_runner}}"]
  variables:
    SPACK_DEVELOP:    "{{job.develop}}"
    STACK_NAME:       "{{job.uenv}}"
    STACK_SYSTEM:     "{{job.system}}"
    SLURM_PARTITION:  "{{job.partition}}"
    STACK_RECIPE:     "{{job.recipe_path}}"
    CSCS_NOTIFICATION_CONTEXT: "build-{{job.uenv}}/{{job.version}}-{{job.system}}/{{job.uarch}}"


test-{{job.uenv}}/{{job.version}}-{{job.system}}/{{job.uarch}}:
  extends: .base-test
  tags: ["{{job.baremetal_runner}}"]
  variables:
    STACK_NAME:       "{{job.uenv}}"
    STACK_SYSTEM:     "{{job.system}}"
    SLURM_PARTITION:  "{{job.partition}}"
    CSCS_NOTIFICATION_CONTEXT: "test-{{job.uenv}}/{{job.version}}-{{job.system}}/{{job.uarch}}"

{% endfor %}

