name: mch-balfrin
store: /user-environment
spack:
  commit: releases/v0.20
  repo: https://github.com/spack/spack.git
description: The compiler toolchains, libraries and tools required to build the MCH production software stack.
