# environments.yaml
gcc-amdgpu:
  views:
    default:
  compiler:
      - toolchain: gcc
        spec: gcc@11.3
  unify: true
  specs:
  - cmake@3.24.4
  - hip@5.3
  - hipify-clang
  - rocthrust
  - rocprim
  - hipcub
  - hdf5 +mpi
  variants:
  - amdgpu_target=gfx90a
  mpi:
    spec: cray-mpich
    gpu: rocm
