nvhpc-env:
  compiler:
    - toolchain: gcc
      spec: gcc@13
    - toolchain: llvm
      spec: nvhpc
  mpi:
    spec: cray-mpich@8.1.30%nvhpc
    gpu: cuda
  unify: true
  specs:
  - quantum-espresso@7.4.1 %nvhpc +libxc +cuda +nvtx +scalapack +elpa +openmp +mpigpu hdf5=parallel
  - netlib-scalapack
  - fftw%nvhpc
  - nvpl-blas threads=openmp
  - nvpl-lapack threads=openmp
  - libxc%nvhpc~cuda
  - cmake
  - elpa%nvhpc +cuda
  - hdf5 %nvhpc
  - nvhpc ~blas ~lapack ~mpi
  packages:
  - git
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90
  views:
    default:
      link: roots
    develop:
      exclude: ['quantum-espresso', 'patchelf', 'git']
      link: roots
