nvfortran:
  compiler: [gcc, nvhpc]
  network:
      mpi: cray-mpich@8.1.32
  unify: true
  specs:
  - aws-ofi-nccl
  - cmake
  - cuda@12.9
  - fftw +openmp
  - fmt
  - hdf5 +fortran+threadsafe+hl
  - libtree
  - lua
  - libtree
  - lz4
  - meson
  - nccl
  - nccl-tests
  - ninja
  - nvpl-blas threads=openmp
  - nvpl-lapack threads=openmp
  - osu-micro-benchmarks
  - python@3.13
  - zlib-ng
  - netcdf-c
  - netcdf-fortran %fortran=nvhpc
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90
  views:
    nvfort:
      link: roots
      uenv:
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
