name: ParaView
store: /user-environment
spack:
  commit: 85d83f9c26cea76051cf95bc7194c43bfa0a0b5a
  repo: https://github.com/spack/spack.git
description: ParaView for grace-hopper using EGL
modules: false
