version: 2
name: paraview
store: /user-environment
spack:
  repo: https://github.com/spack/spack.git
  commit: releases/v1.1
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: 9c604befac9c348ceccf16582fa532dab317958f
description: ParaView for Alps Grace-Hopper clusters using EGL
default-view: default
