version: 2
name: paraview
store: /user-environment
spack:
  repo: https://github.com/spack/spack.git
  commit: releases/v1.1
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: 0ed7eaf328ee495dd4346d2b56e200692d432024
description: ParaView for Alps Grace-Hopper clusters using EGL
default-view: default
